/*
 * File: app/store/StoreEstadosImportarCompraXML.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.store.StoreEstadosImportarCompraXML', {
    extend: 'Ext.data.Store',

    requires: [
        'almacen.model.mdlGeneric',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreEstadosImportarCompraXML',
            model: 'almacen.model.mdlGeneric',
            data: [
                {
                    value: '0',
                    label: 'PENDIENTE'
                },
                {
                    value: '1',
                    label: 'PROCESADO'
                },
                {
                    value: '-1',
                    label: 'ERROR'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});