/*
 * File: app/model/mdlCompraXML.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.model.mdlCompraXML', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'CLAVESUCURSAL'
        },
        {
            name: 'CLAVEPROVEEDOR'
        },
        {
            name: 'CLAVECONTROL'
        },
        {
            name: 'UUID_CFDI'
        },
        {
            name: 'RFC_EMISOR'
        },
        {
            name: 'RFC_RECEPTOR'
        },
        {
            name: 'FECHA_GENERACION'
        },
        {
            name: 'FECHA_IMPORTACION'
        },
        {
            name: 'CLAVEUSUARIO_IMPORTACION'
        },
        {
            name: 'CLAVECOMPRA'
        },
        {
            name: 'CLAVECONTROL_COMPRA'
        },
        {
            name: 'FECHA_EMISION_CFDI'
        },
        {
            name: 'DOCUMENTO_CFDI'
        },
        {
            name: 'IMPORTE_CFDI'
        },
        {
            name: 'ESTADO'
        },
        {
            name: 'OBSERVACIONES_ESTADO'
        },
        {
            name: 'NOMBRE_PROVEEDOR'
        },
        {
            name: 'CFDI'
        }
    ]
});