/*
 * File: app/model/mdlProducciones.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.model.mdlProducciones', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            name: 'claveproduccion'
        },
        {
            name: 'clavesucursal'
        },
        {
            name: 'clavecontrol'
        },
        {
            name: 'claveProducto'
        },
        {
            name: 'concepto'
        },
        {
            name: 'unidad'
        },
        {
            name: 'cantidadEsperada'
        },
        {
            name: 'cantidadProducida'
        },
        {
            name: 'costoEsperado'
        },
        {
            name: 'costoReal'
        },
        {
            type: 'string',
            name: 'estado'
        },
        {
            type: 'date',
            name: 'fechaRegistro',
            dateFormat: 'd/m/Y h:i:s A',
            dateReadFormat: 'd/m/Y h:i:s A',
            dateWriteFormat: 'd/m/Y h:i:s A'
        },
        {
            type: 'date',
            name: 'fechaTerminacion',
            dateFormat: 'd/m/Y h:i:s A',
            dateReadFormat: 'd/m/Y h:i:s A',
            dateWriteFormat: 'd/m/Y h:i:s A'
        },
        {
            type: 'date',
            name: 'fechaCancelacion',
            dateFormat: 'd/m/Y h:i:s A',
            dateReadFormat: 'd/m/Y h:i:s A',
            dateWriteFormat: 'd/m/Y h:i:s A'
        },
        {
            name: 'cveUsrRegistro'
        },
        {
            name: 'cveUsrTerminacion'
        },
        {
            name: 'cveUsrCancelacion'
        },
        {
            name: 'nombreEmpleado'
        },
        {
            name: 'claveEmpleado'
        },
        {
            name: 'importe'
        },
        {
            name: 'precioVenta'
        },
        {
            name: 'claveProductoVenta'
        },
        {
            name: 'tipoPago'
        },
        {
            name: 'cantidadPago'
        },
        {
            name: 'estadoCosto'
        },
        {
            type: 'string',
            allowNull: true,
            defaultValue: null,
            name: 'cantSemaf'
        },
        {
            type: 'string',
            allowNull: true,
            defaultValue: null,
            name: 'colorSemaf'
        },
        {
            name: 'descripcionEtapaActual'
        },
        {
            name: 'descripcionEtapaSiguiente'
        }
    ]
});