/*
 * File: app/view/DlgAsociarProductoViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgAsociarProductoViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgasociarproducto',

    AsociaProducto: function(recBase,recSelected) {
        if ((!Ext.ComponentMgr.get("fldProporcion").isValid()) || (Ext.ComponentMgr.get("fldProporcion").getValue()<=0)) return false;
        Proporcion=Ext.ComponentMgr.get("fldProporcion").getValue();
        ClaveProducto = recSelected.get("claveproducto");
        NombreProducto=recSelected.get("nombreproducto");
        recBase.set("xmlProporcionExterna", Proporcion);
        recBase.set("claveproducto", ClaveProducto);
        recBase.set("nombreproducto", NombreProducto);
        recBase.set("cantidad", recBase.get("xmlCantidad") * Proporcion);
        recBase.set("claveProductoAnterior", ClaveProducto);
        if (recBase.modified.claveproducto!==undefined){
            recBase.set("claveProductoAnterior", recBase.modified.claveproducto);
        }
        Ext.ComponentMgr.get("gridAsociar").getStore().clearFilter();
        Ext.WindowMgr.get("wndAsociaProducto").currentController.actualizaIVA();
        Ext.WindowMgr.get("wndAsociaProducto").close();

    },

    onViewItemDblClick: function(dataview, record, item, index, e, eOpts) {
        recBase = Ext.WindowMgr.get("wndAsociaProducto").currentRecord;
        this.AsociaProducto(recBase,record);
    },

    onButtonClick: function(button, e, eOpts) {
        if (Ext.ComponentMgr.get("gridAsociar").getSelection().length <= 0) return false;

        recBase = Ext.WindowMgr.get("wndAsociaProducto").currentRecord;
        this.AsociaProducto(recBase,Ext.ComponentMgr.get("gridAsociar").getSelection()[0]);
    }

});
