/*
 * File: app/view/DlgBusquedaComprasViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgBusquedaComprasViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgbusquedacompras',

    control: {
        "button#btnAceptarBCompras": {
            click: 'aceptaCargaCompra'
        },
        "button#btnCancelarBCompras": {
            click: 'cerrarVentana'
        }
    },

    aceptaCargaCompra: function(button, e, eOpts) {
        var winBusquedaCompra = Ext.WindowManager.get("wndBusquedaCompras");
        var controller = winBusquedaCompra.parentController;
        if (Ext.ComponentMgr.get("gridBusquedaCompras").getSelectionModel().getSelection().length  <=0) return true;
        var idCompra=Ext.ComponentMgr.get("gridBusquedaCompras").getSelectionModel().getSelection()[0].get("claveCompra");;
        var request = new Object(); request.method="cargacompra"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
        request.params.push({"name":"clavecompra","value":idCompra});
        almacen.getApplication().loadData(request,function(response){
            /*Ext.ComponentMgr.get("gridBusquedaCompras").getStore().loadData(response.compras);
                                                                                Ext.ComponentMgr.get("gridBusquedaCompras").getPicker().loadMask.hide();*/
            controller.cargarCompra(response);
        });
        winBusquedaCompra.close();
        winBusquedaCompra.destroy();
    },

    cerrarVentana: function(button, e, eOpts) {
        var winBusquedaCompra = Ext.WindowManager.get("wndBusquedaCompras");
        winBusquedaCompra.close();
    }

});
