/*
 * File: app/view/DlgBusquedaComprasViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgBusquedaComprasViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgbusquedacompras1',

    control: {
        "button#btnAceptarBCompras1": {
            click: 'aceptaCargaCompra'
        },
        "button#btnCancelarBCompras1": {
            click: 'cerrarVentana'
        },
        "#cmbBProveedor": {
            beforerender: 'loadProveedores',
            beforequery: 'filtraProveedores'
        },
        "button#btnBuscar": {
            click: 'buscarComprasHistorico'
        }
    },

    aceptaCargaCompra: function(button, e, eOpts) {


        var winBusquedaCompra = Ext.WindowManager.get("wndBusquedaCompras1");
        var controller = winBusquedaCompra.parentController;
                if (Ext.ComponentMgr.get("gridBusquedaCompras1").getSelectionModel().getSelection().length  <=0) return true;
                                                                            var idCompra=Ext.ComponentMgr.get("gridBusquedaCompras1").getSelectionModel().getSelection()[0].get("claveCompra");;
                                                                            var request = new Object(); request.method="cargacompraremota"; request.params=[];
                                                                            request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                                                            request.params.push({"name":"clavecompra","value":idCompra});
                                                                            almacen.getApplication().loadData(request,function(response){
                                                                                /*Ext.ComponentMgr.get("gridBusquedaCompras").getStore().loadData(response.compras);
                                                                                Ext.ComponentMgr.get("gridBusquedaCompras").getPicker().loadMask.hide();*/
                                                                                controller.cargarCompra(response);
                                                                            });
                                                                            winBusquedaCompra.close();
                                                                            winBusquedaCompra.destroy();
    },

    cerrarVentana: function(button, e, eOpts) {
        var winBusquedaCompra = Ext.WindowManager.get("wndBusquedaCompras1");
        winBusquedaCompra.close();
    },

    loadProveedores: function(component, eOpts) {
        var request = new Object(); request.method="proveedores"; request.params=[];
                                    request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                    almacen.getApplication().loadData(request,function(response){
                                        component.getStore().loadData(response.proveedores);
                                        component.getStore().sort('nombreProveedor','ASC');
                                        //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();


                                    });
    },

    buscarComprasHistorico: function(button, e, eOpts) {

        var dtInicio = Ext.ComponentMgr.get("dtInicial");
        var dtFinal = Ext.ComponentMgr.get("dtFinal");
        var cmbBProveedor = Ext.ComponentMgr.get("cmbBProveedor");
        var esValidaFecha = (dtInicio.isValid() && dtFinal.isValid());

        var esValidoProveedor=cmbBProveedor.isValid();
        var request = {}; request.method="busquedahistorico"; request.params=[];
        request.params.push({"name":"imei", "value": almacen.getApplication().SessionId});
        if (esValidaFecha){
            if (esValidaFecha){
                request.params.push({"name":"fechaInicio", "value": dtInicio.getRawValue()});
                request.params.push({"name":"fechaFin", "value": dtFinal.getRawValue()});
            }
            if (esValidoProveedor){
                request.params.push({"name":"claveProveedor", "value": cmbBProveedor.getValue()});
            }
            var winBusquedaCompra = Ext.WindowManager.get("wndBusquedaCompras1");
            var el = winBusquedaCompra.getEl();
            el.mask('Realizando consulta, por favor espere');
            almacen.getApplication().loadData(request,function(response){
                Ext.ComponentMgr.get("gridBusquedaCompras1").getStore().loadData(response.compras);
                el.unmask();
            },function(){
                el.unmask();
            });

        }else{
            Ext.Msg.alert('', 'Por favor especifique un filtro antes de realizar la búsqueda.');
        }
    },

    filtraProveedores: function(queryPlan, eOpts) {


             queryPlan.query = new RegExp(queryPlan.query, 'i');
             queryPlan.forceAll = true;
    }

});
