/*
 * File: app/view/DlgBusquedaCompras1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgBusquedaCompras1', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgbusquedacompras1',

    requires: [
        'almacen.view.DlgBusquedaComprasViewModel1',
        'almacen.view.DlgBusquedaComprasViewController1',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.filters.filter.Number',
        'Ext.grid.column.Date',
        'Ext.grid.filters.filter.Date',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.grid.filters.Filters'
    ],

    config: {
        parentController: null
    },

    controller: 'dlgbusquedacompras1',
    viewModel: {
        type: 'dlgbusquedacompras1'
    },
    autoScroll: true,
    height: 456,
    id: 'wndBusquedaCompras1',
    width: 732,
    title: 'Buscar Compras',
    modal: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            style: 'background-color: #141314;',
            layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    id: 'btnCancelarBCompras1',
                    icon: '\'http://icons.iconarchive.com/icons/led24.de/led/16/cancel-icon.png\'',
                    text: 'Cerrar'
                },
                {
                    xtype: 'button',
                    id: 'btnAceptarBCompras1',
                    icon: '\'https://glnd.alexanderstreet.com/ui/common/playlist.png\'',
                    text: 'Aceptar'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            layout: 'column',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'datefield',
                    id: 'dtInicial',
                    fieldLabel: 'Fecha Inicio',
                    hideLabel: true,
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Fecha Inicial',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'datefield',
                    id: 'dtFinal',
                    fieldLabel: 'Fecha Fin',
                    hideLabel: true,
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'Fecha Final',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'combobox',
                    id: 'cmbBProveedor',
                    fieldLabel: '',
                    allowBlank: false,
                    emptyText: 'Proveedor',
                    displayField: 'nombreProveedor',
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'StoreProveedores',
                    valueField: 'claveProveedor'
                },
                {
                    xtype: 'button',
                    id: 'btnBuscar',
                    icon: 'resources/search.png',
                    text: 'Buscar'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            autoScroll: true,
            id: 'gridBusquedaCompras1',
            overlapHeader: false,
            title: '',
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            enableColumnResize: false,
            forceFit: true,
            reserveScrollbar: true,
            store: 'StoreGridCompras',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'claveCompra',
                    text: 'Numero Compra',
                    filter: {
                        type: 'number'
                    }
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'fechaCompra',
                    text: 'Fecha',
                    format: 'd/m/Y',
                    filter: {
                        type: 'date'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'proveedor',
                    text: 'Proveedor',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Total',
                    text: 'Total',
                    filter: {
                        type: 'number'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'numeroFactura',
                    text: 'Factura'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'estado',
                    text: 'Estado',
                    filter: {
                        type: 'list'
                    }
                }
            ],
            selModel: {
                selType: 'rowmodel'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        }
    ]

});