/*
 * File: app/view/DlgConsultaTraspasosViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgConsultaTraspasosViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgconsultatraspasos',

    control: {
        "#cmbTEstado": {
            afterrender: 'loadEstados',
            beforequery: 'filtraEstados'
        },
        "#wndConsultaTraspasos": {
            afterrender: 'initConsulta'
        },
        "button#btnFiltrar": {
            click: 'ConsultarTraspasos'
        },
        "button#btnPendientes": {
            click: 'consultarPendientes'
        },
        "button#btnCancela": {
            click: 'CancelaTraspaso'
        },
        "button#btnRecibe": {
            click: 'RecibeTraspaso'
        },
        "button#btnFinaliza": {
            click: 'FinalizaTraspasos'
        },
        "button#btnDetalle1": {
            click: 'showDetail'
        }
    },

    loadEstados: function(component, eOpts) {
        var request = new Object(); request.method="estadostraspasos"; request.params=[];
                                    request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                    almacen.getApplication().loadData(request,function(response){
                                        component.getStore().loadData(response.items);
                                        component.getStore().sort('label','ASC');
                                        //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                                    });
    },

    filtraEstados: function(queryPlan, eOpts) {
         queryPlan.query = new RegExp(queryPlan.query, 'i');
         queryPlan.forceAll = true;
    },

    initConsulta: function(component, eOpts) {
        var currentController = this;
        var component = Ext.ComponentMgr.get("gridConsultaTraspasos");
        component.getStore().removeAll();
        window.setTimeout(function(){currentController.loadConsultaTraspasos(null,null);}, 2000);
    },

    ConsultarTraspasos: function(button, e, eOpts) {
        var dtInicial = Ext.ComponentMgr.get("dtTInicial");
        var dtFinal = Ext.ComponentMgr.get("dtTFinal");
        var cmbEstado = Ext.ComponentMgr.get("cmbTEstado");
        if (dtInicial.isValid() && dtFinal.isValid()){ //los 2 campos de fechas deben ser válidos
           var pFechaInicial = dtInicial.getRawValue();
           var pFechaFinal = dtFinal.getRawValue();
           var pEstado;
           if (cmbEstado.isValid()){
               pEstado = cmbEstado.getValue();
           }
           var pFiltroFecha = "TO_DATE('" + pFechaInicial + "', 'DD/MM/YYYY')" + "|TO_DATE('" + pFechaFinal + "', 'DD/MM/YYYY')";;
           this.loadConsultaTraspasos(pEstado, pFiltroFecha);
        }else{
            Ext.Msg.alert('', 'Por favor especifique un filtro antes de realizar la búsqueda.');
        }

    },

    consultarPendientes: function(button, e, eOpts) {
        this.loadConsultaTraspasos(null,null);
    },

    CancelaTraspaso: function(button, e, eOpts) {

        var currentController=this;
        Ext.Msg.confirm("Cancelar Traspaso", "¿Desea cancelar el traspaso " + button.currentRecord.ClaveTraspaso,
        function(buttonId){
            if (buttonId == 'yes'){
                var winBusquedaCompra = Ext.WindowManager.get("wndConsultaTraspasos");
                var el = winBusquedaCompra.getEl();
                el.mask('Cancelando traspaso, por favor espere');
                var request = new Object(); request.method="cancelatraspasos"; request.params=[];
                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                request.params.push({"name":"traspaso","value":Ext.encode(button.currentRecord)});
                almacen.getApplication().loadData(request,function(response){
                    el.unmask();
                    currentController.loadConsultaTraspasos(null,null);
                    if (Ext.WindowManager.get("wndDetallePedidos"))
                            Ext.WindowManager.get("wndDetallePedidos").close();
                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                });
            }
        });
    },

    RecibeTraspaso: function(button, e, eOpts) {
        var currentController=this;

        console.log(button.currentRecord);


        var msg = "¿Desea recibir el traspaso " + button.currentRecord.ClaveTraspaso + "?";

        if(button.currentRecord.tipoPago === 15){
            msg = "El traspaso viene con pago en EFECTIVO. <br> ¿Desea recibir el traspaso " + button.currentRecord.ClaveTraspaso + " en EFECTIVO?";
        }

        Ext.Msg.confirm("Recibir Traspaso", msg,
                        function(buttonId){
                            if (buttonId == 'yes'){
                                var winBusquedaCompra = Ext.WindowManager.get("wndConsultaTraspasos");
                                var el = winBusquedaCompra.getEl();
                                el.mask('Recibiendo traspaso, por favor espere');
                                var request = new Object(); request.method="recibetraspasos"; request.params=[];
                                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                request.params.push({"name":"traspaso","value":Ext.encode(button.currentRecord)});
                                almacen.getApplication().loadData(request,function(response){
                                    el.unmask();
                                    currentController.loadConsultaTraspasos(null,null);
                                    if (Ext.WindowManager.get("wndDetallePedidos"))
                                        Ext.WindowManager.get("wndDetallePedidos").close();

                                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                                });
                            }
                        });
    },

    FinalizaTraspasos: function(button, e, eOpts) {
        var currentController=this;
                Ext.Msg.confirm("Finalizar Traspaso", "¿Desea finalizar el traspaso " + button.currentRecord.ClaveTraspaso,
                function(buttonId){
                    if (buttonId == 'yes'){
                        var winBusquedaCompra = Ext.WindowManager.get("wndConsultaTraspasos");
                        var el = winBusquedaCompra.getEl();
                        el.mask('Finalizando traspaso, por favor espere');
                        var request = new Object(); request.method="finalizatraspasos"; request.params=[];
                        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                        request.params.push({"name":"traspaso","value":Ext.encode(button.currentRecord)});
                        almacen.getApplication().loadData(request,function(response){
                            el.unmask();
                            currentController.loadConsultaTraspasos(null,null);
                            //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                        });
                    }
                });
    },

    showDetail: function(button, e, eOpts) {
        var request = new Object(); request.method="consultadetalletraspasos"; request.params=[];
                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                request.params.push({"name":"clavetraspaso","value":button.currentRecord.ClaveTraspaso});
                window.currentPedido = null;
                var component = Ext.ComponentMgr.get("gridConsultaTraspasos1");
                 var currentController=this;
                //component.getStore().removeAll();
                almacen.getApplication().loadData(request,function(response){
                    window.currentPedido = response;
                    var wnd=Ext.create("almacen.view.DlgConsultaTraspaso", {id:"wndDetallePedidos",currentRecord:response});
                        wnd.parentController=currentController;
                        wnd.currentRecord=response;
                        wnd.center();
                        wnd.show();
                    //el.unmask();
                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                },function(response){
                    el.unmask();

                });

    },

    loadConsultaTraspasos: function(FiltroEstado,FiltroFechas) {

        var winBusquedaCompra = Ext.WindowManager.get("wndConsultaTraspasos");
        var el = winBusquedaCompra.getEl();
        el.mask('Realizando consulta, por favor espere');
        var request = new Object(); request.method="consultatraspasos"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
        if (FiltroEstado)request.params.push({"name":"filtroEstado","value":FiltroEstado});
        if (FiltroFechas)request.params.push({"name":"filtroFecha","value":FiltroFechas});
        var component = Ext.ComponentMgr.get("gridConsultaTraspasos");
        component.getStore().removeAll();
        almacen.getApplication().loadData(request,function(response){
            component.getStore().loadData(response.traspasos);
            el.unmask();
            //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
        },function(response){
            el.unmask();

        });
    }

});
