/*
 * File: app/view/DlgConsultaTraspaso.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgConsultaTraspaso', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgconsultatraspaso',

    requires: [
        'almacen.view.DlgConsultaPedidoViewModel1',
        'almacen.view.DlgConsultaPedidoViewController1',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'dlgconsultatraspaso',
    viewModel: {
        type: 'dlgconsultatraspaso'
    },
    height: 601,
    width: 850,
    layout: 'border',
    title: 'Datos Traspaso',

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            id: 'gridProductos1',
            title: 'Productos',
            store: 'StoreGridProductos',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'claveproducto',
                    text: 'Clave'
                },
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'nombreproducto',
                    text: 'Producto'
                },
                {
                    xtype: 'gridcolumn',
                    width: 125,
                    defaultWidth: 120,
                    dataIndex: 'cantidad',
                    text: 'Cantidad'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'importe',
                    formatter: '',
                    text: 'Importe'
                }
            ],
            listeners: {
                afterrender: 'onGridProductosAfterRender'
            }
        },
        {
            xtype: 'gridpanel',
            region: 'north',
            height: 211,
            id: 'gridPedido1',
            title: '',
            hideHeaders: true,
            store: 'StoreDatosPedido',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 273,
                    dataIndex: 'label',
                    text: '.'
                },
                {
                    xtype: 'gridcolumn',
                    width: 345,
                    dataIndex: 'value',
                    text: '.'
                }
            ],
            listeners: {
                afterrender: 'onGridPedidoAfterRender'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    id: 'btnCancelaPedido1',
                    icon: 'resources/cancel-icon.png',
                    text: 'Cancelar Traspaso',
                    listeners: {
                        click: 'CallCancelaPedido'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    id: 'btnRecibePedido1',
                    icon: 'resources/receive.png',
                    text: 'Recibir',
                    listeners: {
                        click: 'RecibePedido'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    id: 'btnFinalizaPedido1',
                    icon: 'resources/tick.png',
                    text: 'Finalizar',
                    listeners: {
                        click: 'FinalizaPedido'
                    }
                }
            ]
        }
    ]

});