/*
 * File: app/view/DlgConsultaTraspasosViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgConsultaTraspasosViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgconsultatraspasos1',

    control: {
        "#cmbTEstado1": {
            afterrender: 'loadEstados',
            beforequery: 'filtraEstados'
        },
        "#wndConsultaPedidos": {
            afterrender: 'initConsulta'
        },
        "button#btnFiltrar1": {
            click: 'ConsultarTraspasos'
        },
        "button#btnPendientes1": {
            click: 'consultarPendientes'
        },
        "button#btnCancela1": {
            click: 'CancelaTraspaso'
        },
        "button#btnRecibe1": {
            click: 'RecibeTraspaso'
        },
        "button#btnFinaliza1": {
            click: 'FinalizaTraspasos'
        },
        "button#btnDetalle": {
            click: 'showDetail'
        }
    },

    loadEstados: function(component, eOpts) {
        var request = new Object(); request.method="estadospedidos"; request.params=[];
                                    request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                    almacen.getApplication().loadData(request,function(response){
                                        component.getStore().loadData(response.items);
                                        component.getStore().sort('label','ASC');
                                        //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                                    });
    },

    filtraEstados: function(queryPlan, eOpts) {
         queryPlan.query = new RegExp(queryPlan.query, 'i');
         queryPlan.forceAll = true;
    },

    initConsulta: function(component, eOpts) {
        var currentController = this;
        var component = Ext.ComponentMgr.get("gridConsultaTraspasos1");
        component.getStore().removeAll();
        window.setTimeout(function(){currentController.loadConsultaTraspasos(null,null);}, 2000);
    },

    ConsultarTraspasos: function(button, e, eOpts) {
        var dtInicial = Ext.ComponentMgr.get("dtTInicial1");
        var dtFinal = Ext.ComponentMgr.get("dtTFinal1");
        var cmbEstado = Ext.ComponentMgr.get("cmbTEstado1");
        if (dtInicial.isValid() && dtFinal.isValid()){ //los 2 campos de fechas deben ser válidos
            var pFechaInicial = dtInicial.getRawValue();
            var pFechaFinal = dtFinal.getRawValue();
            var pEstado;
            if (cmbEstado.isValid()){
                pEstado = cmbEstado.getValue();
            }
            var pFiltroFecha = "TO_DATE('" + pFechaInicial + "', 'DD/MM/YYYY')" + "|TO_DATE('" + pFechaFinal + "', 'DD/MM/YYYY')";;
            this.loadConsultaTraspasos(pEstado, pFiltroFecha);
        }else{
            Ext.Msg.alert('', 'Por favor especifique un filtro antes de realizar la búsqueda.');
        }

    },

    consultarPendientes: function(button, e, eOpts) {
        this.loadConsultaTraspasos(null,null);
    },

    CancelaTraspaso: function(button, e, eOpts) {

        var currentController=this;
        Ext.Msg.confirm("Cancelar Pedido", "¿Desea cancelar el pedido " + button.currentRecord.clavePedido,
                        function(buttonId){
                            if (buttonId == 'yes'){
                                var winBusquedaCompra = Ext.WindowManager.get("wndConsultaPedidos");
                                var el = winBusquedaCompra.getEl();
                                el.mask('Cancelando pedido, por favor espere');
                                var request = new Object(); request.method="cancelapedido"; request.params=[];
                                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                request.params.push({"name":"pedido","value":Ext.encode(button.currentRecord)});
                                almacen.getApplication().loadData(request,function(response){
                                    el.unmask();
                                    currentController.loadConsultaTraspasos(null,null);
                                    if (Ext.WindowManager.get("wndDetallePedidos"))
                                        Ext.WindowManager.get("wndDetallePedidos").close();
                                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                                });
                            }
                        });
    },

    RecibeTraspaso: function(button, e, eOpts) {
        var currentController=this;
        Ext.Msg.confirm("Recibir Pedido", "¿Desea recibir el pedido " + button.currentRecord.clavePedido + "?",
                        function(buttonId){
                            if (buttonId == 'yes'){
                                var winBusquedaCompra = Ext.WindowManager.get("wndConsultaPedidos");
                                var el = winBusquedaCompra.getEl();
                                if (eOpts != null && eOpts.wnd != null)
                                    el=eOpts.wnd.getEl();
                                console.log(el);
                                el.mask('Recibiendo pedido, por favor espere');
                                var request = new Object(); request.method="recibepedido"; request.params=[];
                                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                                request.params.push({"name":"pedido","value":Ext.encode(button.currentRecord)});
                                console.log(request);
                                almacen.getApplication().loadData(request,function(response){
                                    console.log(response);
                                    el.unmask();
                                    currentController.loadConsultaTraspasos(null,null);
                                    if (Ext.WindowManager.get("wndDetallePedidos"))
                                        Ext.WindowManager.get("wndDetallePedidos").close();
                                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                                    almacen.getApplication().downloadCompra(response.clave, "printcompra");
                                });
                            }
                        });
    },

    FinalizaTraspasos: function(button, e, eOpts) {
        var currentController=this;
                Ext.Msg.confirm("Finalizar Pedido", "¿Desea finalizar el pedido " + button.currentRecord.clavePedido,
                function(buttonId){
                    if (buttonId == 'yes'){
                        var winBusquedaCompra = Ext.WindowManager.get("wndConsultaPedidos");
                        var el = winBusquedaCompra.getEl();
                        el.mask('Finalizando pedido, por favor espere');
                        var request = new Object(); request.method="finalizapedidos"; request.params=[];
                        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                        request.params.push({"name":"pedido","value":Ext.encode(button.currentRecord)});
                        almacen.getApplication().loadData(request,function(response){
                            el.unmask();
                            currentController.loadConsultaTraspasos(null,null);
                            if (Ext.WindowManager.get("wndDetallePedidos"))
                                Ext.WindowManager.get("wndDetallePedidos").close();
                            //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                        });
                    }
                });
    },

    showDetail: function(button, e, eOpts) {
        var request = new Object(); request.method="consultapedidos"; request.params=[];
                request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
                request.params.push({"name":"clavepedido","value":button.currentRecord.clavePedido});
                request.params.push({"name":"pedido","value":Ext.encode(button.currentRecord)});
                window.currentPedido = null;
                var component = Ext.ComponentMgr.get("gridConsultaTraspasos1");
                //component.getStore().removeAll();
                var currentController = this;
                almacen.getApplication().loadData(request,function(response){
                    window.currentPedido = response;
                    var wnd=Ext.create("almacen.view.DlgConsultaPedido", {id:"wndDetallePedidos",currentRecord:response});
                        wnd.parentController=currentController;
                        wnd.currentRecord=response;
                        wnd.center();
                        wnd.show();
                    //el.unmask();
                    //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
                },function(response){
                    el.unmask();

                });



    },

    loadConsultaTraspasos: function(FiltroEstado,FiltroFechas, pedido) {

        var winBusquedaCompra = Ext.WindowManager.get("wndConsultaPedidos");
        var el = winBusquedaCompra.getEl();
        el.mask('Realizando consulta, por favor espere');
        var request = new Object(); request.method="consultapedidos"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});

        if (FiltroEstado)request.params.push({"name":"filtroEstado","value":FiltroEstado});
        if (FiltroFechas)request.params.push({"name":"filtroFecha","value":FiltroFechas});
        var component = Ext.ComponentMgr.get("gridConsultaTraspasos1");
        component.getStore().removeAll();
        almacen.getApplication().loadData(request,function(response){
            component.getStore().loadData(response.pedidos);
            el.unmask();
            //Ext.ComponentMgr.get("comboProveedor").getPicker().loadMask.hide();
        },function(response){
            el.unmask();

        });
    }

});
