/*
 * File: app/view/DlgConsultaCompraXML.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgConsultaCompraXML', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgconsultaCompraXML',

    requires: [
        'almacen.view.DlgConsultaCompraXMLViewModel',
        'almacen.view.DlgConsultaCompraXMLViewController',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.selection.RowModel',
        'Ext.grid.filters.Filters',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox'
    ],

    controller: 'dlgconsultacompraxml',
    viewModel: {
        type: 'dlgconsultacompraxml'
    },
    height: 581,
    width: 935,
    layout: 'border',
    title: 'Consulta pedidos',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            id: 'gridConsultaTraspasos3',
            title: '',
            allowDeselect: true,
            store: 'StoreImportarCompraXML',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 114,
                    dataIndex: 'UUID_CFDI',
                    text: 'UUID'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 180,
                    minWidth: 180,
                    weight: 180,
                    width: 258,
                    defaultWidth: 180,
                    dataIndex: 'NOMBRE_PROVEEDOR',
                    text: 'Proveedor',
                    flex: 1
                },
                {
                    xtype: 'datecolumn',
                    maxWidth: 180,
                    minWidth: 180,
                    weight: 180,
                    width: 160,
                    defaultWidth: 180,
                    dataIndex: 'FECHA_GENERACION',
                    text: 'Fecha Registro',
                    format: 'd/m/Y H:i:s'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var ds = {"1":"PROCESADO","0":"PENDIENTE","-1":"ERROR"};
                        var theValue = ds[""+value];
                        return theValue;

                    },
                    width: 126,
                    dataIndex: 'ESTADO',
                    text: 'Estado'
                },
                {
                    xtype: 'numbercolumn',
                    renderer: function(value, metaData, record,  rowIndex, colIndex, store, view) {

                        return Ext.util.Format.currency(value);

                    },
                    width: 118,
                    align: 'right',
                    dataIndex: 'IMPORTE_CFDI',
                    text: 'Total',
                    format: '0,000.000',
                    filter: {
                        type: 'number'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'btnCancela3',
                            icon: 'resources/cancel-icon.png',
                            text: 'Cancelar Factura'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'btnRecibe3',
                            icon: 'resources/receive.png',
                            overflowText: '',
                            text: 'Importar Factura'
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'rowmodel',
                allowDeselect: true,
                mode: 'SINGLE',
                listeners: {
                    selectionchange: 'onRowModelSelectionChange'
                }
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ],
            listeners: {
                afterrender: {
                    fn: 'onGridConsultaTraspasos3AfterRender',
                    scope: 'controller'
                }
            }
        },
        {
            xtype: 'form',
            region: 'north',
            height: 50,
            layout: 'column',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'datefield',
                    id: 'dtTInicial3',
                    width: 150,
                    fieldLabel: '',
                    allowBlank: false,
                    emptyText: 'Fecha Inicial',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'datefield',
                    id: 'dtTFinal3',
                    width: 150,
                    fieldLabel: '',
                    allowBlank: false,
                    emptyText: 'Fecha Final',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'combobox',
                    id: 'cmbTEstado3',
                    width: 150,
                    fieldLabel: '',
                    allowBlank: false,
                    emptyText: 'Estado',
                    displayField: 'label',
                    queryMode: 'local',
                    store: 'StoreEstadosImportarCompraXML',
                    valueField: 'value'
                },
                {
                    xtype: 'button',
                    id: 'btnFiltrar3',
                    icon: 'resources/filter.gif',
                    text: 'Filtrar',
                    listeners: {
                        click: {
                            fn: 'onBtnFiltrar3Click',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnPendientes3',
                    icon: 'resources/pending.png',
                    text: 'Pendientes'
                }
            ]
        }
    ],

    onRowModelSelectionChange: function(model, selected, eOpts) {
        Ext.ComponentMgr.get("btnCancela3").setDisabled(true);
        Ext.ComponentMgr.get("btnRecibe3").setDisabled(true);

        Ext.ComponentMgr.get("btnCancela3").currentRecord=null;
        Ext.ComponentMgr.get("btnRecibe3").currentRecord=null;


        if (selected.length <= 0) return;
        var rec = selected[0];
        var estado = parseInt(rec.get("ESTADO"), 10);
        if   (estado == 0) {
            Ext.ComponentMgr.get("btnCancela3").setDisabled(false);//habilitamos el boton para cancelar
            Ext.ComponentMgr.get("btnCancela3").currentRecord=rec.data;
            Ext.ComponentMgr.get("btnRecibe3").setDisabled(false);//habilitamos el boton para cancelar
            Ext.ComponentMgr.get("btnRecibe3").currentRecord=rec.data;
        }
    }

});