/*
 * File: app/view/DlgExistenciaAlerta.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgExistenciaAlerta', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgexistenciaalerta',

    requires: [
        'almacen.view.DlgPreciosAlertaViewModel1',
        'almacen.view.DlgPreciosAlertaViewController1',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    config: {
        parentController: null
    },

    controller: 'dlgexistenciaalerta',
    viewModel: {
        type: 'dlgexistenciaalerta'
    },
    height: 400,
    id: 'wndPreciosAlerta1',
    width: 502,
    layout: 'fit',
    title: '',
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'gridProductosPrecios1',
            title: 'La(s) siguiente(s) materia(s) prima(s) excede(n) en 2 o más veces su límite máximo:',
            titleAlign: 'center',
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            enableColumnResize: false,
            forceFit: true,
            store: 'StoreExistenciasAlerta',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Clave',
                    text: 'Clave'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Concepto',
                    text: 'Descripcion'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Unidad',
                    text: 'Unidad'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'proveedorMateria',
                    text: 'Cantidad Máxima'
                }
            ],
            viewConfig: {
                width: 304
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    style: 'background-color: #141314;',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'passwordAutorizacionProductoPrecio1',
                            fieldLabel: '',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'Password Supervisor',
                            emptyText: 'Password Supervisor'
                        },
                        {
                            xtype: 'button',
                            id: 'aceptaAlerta1',
                            icon: 'resources/padlock_s.png',
                            text: 'Autorizar'
                        }
                    ]
                }
            ]
        }
    ]

});