/*
 * File: app/view/dlgHistorico.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.dlgHistorico', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgHistorico',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View'
    ],

    height: 458,
    width: 669,
    layout: 'fit',
    title: 'Historial',
    titleAlign: 'center',
    titleCollapse: true,
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            height: 711,
            width: 994,
            bodyPadding: 10,
            bodyStyle: 'background-color: #D9D8D8;',
            title: '',
            titleAlign: 'center',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    frame: true,
                    id: 'panelProducciones',
                    margin: '0 10 0 0',
                    width: 288,
                    title: 'Producciones',
                    titleAlign: 'center',
                    columnLines: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    forceFit: true,
                    store: 'StoreHistoricoProd',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 53,
                            dataIndex: 'claveproducto',
                            text: 'Clave'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nombreproducto',
                            text: 'Concepto'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 65,
                            dataIndex: 'cantidad',
                            text: 'Cantidad'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 80,
                            dataIndex: 'unidad',
                            text: 'Unidad'
                        }
                    ],
                    viewConfig: {
                        border: '',
                        frame: true,
                        margin: '',
                        loadingText: 'Cargando..'
                    }
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    frame: true,
                    id: 'panelConsumos',
                    margin: '0 0 0 10',
                    frameHeader: false,
                    title: 'Materia Consumida',
                    titleAlign: 'center',
                    columnLines: true,
                    forceFit: true,
                    store: 'StoreHistoricoCons',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 53,
                            dataIndex: 'claveproducto',
                            text: 'Clave'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nombreproducto',
                            text: 'Concepto'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 65,
                            dataIndex: 'cantidad',
                            text: 'Consumido'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'ProporcionAplicar',
                            text: 'Producido'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 80,
                            dataIndex: 'unidad',
                            text: 'Unidad'
                        }
                    ],
                    viewConfig: {
                        loadingText: 'Cargando...'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    },

    onWindowAfterRender: function(component, eOpts) {
        var gridProducciones = Ext.ComponentMgr.get("panelProducciones");
        var gridConsumo = Ext.ComponentMgr.get("panelConsumos");
        var storeProducciones = gridProducciones.getStore();
        var storeConsumo = gridConsumo.getStore();
        storeProducciones.removeAll();
        storeConsumo.removeAll();
        //var request = new Object(); request.method="consultaproducciones"; request.params=[];
        var request = new Object(); request.method="consultaproduccionessimples"; request.params=[];

        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});

        almacen.getApplication().loadData(request,function(response){
            console.log("response");
            console.log(response);
            storeProducciones.loadData(response.producidos);
            storeConsumo.loadData(response.consumidos);
        });


    }

});