/*
 * File: app/view/DlgLogin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgLogin', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlglogin',

    requires: [
        'almacen.view.DlgLoginViewModel',
        'almacen.view.DlgLoginViewController',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'dlglogin',
    viewModel: {
        type: 'dlglogin'
    },
    height: 346,
    id: 'WndLogin',
    resizable: false,
    width: 322,
    closable: false,
    title: 'Iniciar Sesi\u00f3n',
    titleAlign: 'center',
    modal: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    height: 200,
                    style: 'display: block;    margin-left: auto;    margin-right: auto',
                    width: 150,
                    src: 'resources/Logo-Telnet.png'
                },
                {
                    xtype: 'textfield',
                    id: 'passwordTextFieldLogeo',
                    fieldLabel: 'Password',
                    labelAlign: 'top',
                    labelStyle: 'text-align:center',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    enableKeyEvents: true
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    id: 'btnLogin',
                    icon: 'resources/padlock_s.png',
                    text: 'Iniciar Sesión'
                }
            ]
        }
    ]

});