/*
 * File: app/view/DlgMotivosAjustes.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgMotivosAjustes', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgmotivosajustes',

    requires: [
        'almacen.view.DlgNoImpresionesAjustesViewModel1',
        'almacen.view.DlgNoImpresionesAjustesViewController1',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'dlgmotivosajustes',
    viewModel: {
        type: 'dlgmotivosajustes'
    },
    height: 121,
    width: 177,
    closable: false,
    title: 'Seleccione un Motivo',
    modal: true,

    items: [
        {
            xtype: 'combobox',
            id: 'cmbNoImpresiones1',
            fieldLabel: '',
            displayField: 'label',
            queryMode: 'local',
            store: 'StoreMotivosAjuste',
            valueField: 'value'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            id: 'tbNoImpresiones1',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnAceptar1',
                    icon: 'resources/tick.png',
                    text: 'Aceptar'
                }
            ]
        }
    ]

});