/*
 * File: app/view/DlgMotivosOrdenCompleta.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgMotivosOrdenCompleta', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgmotivosordencompleta',

    requires: [
        'almacen.view.DlgNoImpresionesAjustesViewModel2',
        'almacen.view.DlgNoImpresionesAjustesViewController2',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'dlgmotivosordencompleta',
    viewModel: {
        type: 'dlgmotivosordencompleta'
    },
    height: 150,
    width: 300,
    title: 'Compra Incompleta<br><br>Seleccione un motivo por el cual  recibe <br>la compra incompleta.',
    modal: true,

    items: [
        {
            xtype: 'combobox',
            validator: function(value) {
                console.log("value");
                console.log(value);
                Ext.ComponentMgr.get("cmbNoImpresiones2").setValue(value);

                if(value.trim() !== '' && value.trim().length > 0)
                return true;
                else
                return "El campo no puede quedar vacio.";
            },
            id: 'cmbNoImpresiones2',
            width: 295,
            fieldLabel: '',
            allowBlank: false,
            maxLength: 50,
            maxLengthText: 'Longitud máxima {0}',
            displayField: 'label',
            queryMode: 'local',
            store: 'StoreGeneric',
            valueField: 'value'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            id: 'tbNoImpresiones2',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnAceptar2',
                    icon: 'resources/tick.png',
                    text: 'Aceptar'
                }
            ]
        }
    ]

});