/*
 * File: app/view/DlgNoImpresionesAjustesViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgNoImpresionesAjustesViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgnoimpresionesajustes',

    control: {
        "button#btnAceptar": {
            click: 'AsignarPreguntaImpresiones'
        }
    },

    AsignarPreguntaImpresiones: function(button, e, eOpts) {
                var noImpresiones = Ext.ComponentMgr.get("cmbNoImpresiones").getValue();
                var motivo = Ext.WindowMgr.get("wndPreguntaImpresiones").currentMotivoAjuste;
                Ext.WindowMgr.get("wndPreguntaImpresiones").parentController.registrarAjustes(noImpresiones, motivo);
                Ext.WindowMgr.get("wndPreguntaImpresiones").close();
    }

});
