/*
 * File: app/view/DlgNoImpresionesAjustesViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgNoImpresionesAjustesViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgmotivosajustes',

    control: {
        "button#btnAceptar1": {
            click: 'AsignarPreguntaMotivos'
        },
        "#cmbNoImpresiones1": {
            afterrender: 'PreguntaMotivos'
        }
    },

    AsignarPreguntaMotivos: function(button, e, eOpts) {
        var motivo = Ext.ComponentMgr.get("cmbNoImpresiones1").getValue();
        this.AsignaMotivo(motivo);

    },

    PreguntaMotivos: function(component, eOpts) {
        var request = {}; request.method="obtienemotivos"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
        console.log(component.ownerCt);
        var motivo = component.ownerCt.currentMotivoAjuste;
        request.params.push({"name":"tipo","value":motivo});
        var currentController=this;
        almacen.getApplication().loadData(request,function(response){
            if (response.items.length==1){
                currentController.AsignaMotivo(response.items[0].value);
            }else if (response.items.length > 1){
                component = Ext.ComponentMgr.get("cmbNoImpresiones1");
                component.getStore().loadData(response.items);
                component.setValue(response.items[0].value);
            }
        });
    },

    AsignaMotivo: function(motivo) {
                Ext.WindowMgr.get("wndPreguntaMotivos").parentController.preguntarNoImpresiones(motivo);
                Ext.WindowMgr.get("wndPreguntaMotivos").close();
    }

});
