/*
 * File: app/view/DlgPreciosAlertaViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgPreciosAlertaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgpreciosalerta',

    control: {
        "button#aceptaAlerta": {
            click: 'aceptarAlertaClick'
        },
        "#passwordAutorizacionProductoPrecio": {
            keyup: 'aceptarAlertaText'
        },
        "button#Aceptar": {
            click: 'AceptarClickA'
        },
        "button": {
            click: 'CancelarClickA'
        }
    },

    aceptarAlertaClick: function(button, e, eOpts) {
               this.validarAceptarAlerta();
    },

    aceptarAlertaText: function(textfield, e, eOpts) {
                        if (e.getKey()==Ext.event.Event.ENTER){
                                this.validarAceptarAlerta();
                            }
    },

    AceptarClickA: function(button, e, eOpts) {
        this.aceptarClick();
    },

    CancelarClickA: function(button, e, eOpts) {
        this.cancelarClick();
    },

    validarAceptarAlerta: function() {
        var ventana=Ext.WindowManager.get("wndPreciosAlerta");
        var controller=ventana.parentController;
        var request = new Object(); request.method="validaSupervisor"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId},{"name":"USERNAME","value":Ext.ComponentMgr.get("passwordAutorizacionProductoPrecio").getValue()});
        almacen.getApplication().loadData(request,function(response){
            if(response.status){
               controller.guardaCompra();
               ventana.close();

            }else{
                Ext.Msg.alert('', 'Usuario o contraseña incorrecto.');
            }
        });
    },

    aceptarClick: function() {
        //////debugger;
        var controller=Ext.WindowManager.get("wndPreciosAlerta").parentController;
                    controller.guardaCompra();
                    Ext.WindowManager.get("wndPreciosAlerta").close();
    },

    cancelarClick: function() {
        Ext.WindowManager.get("wndPreciosAlerta").close();
    },

    requiereAutorizacion: function() {

        var request = new Object(); request.method="requiereautorizacion"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
        almacen.getApplication().loadData(request,function(response){

            if(response.status){

                var cp = Ext.getCmp('MyToolbar6');
                cp.show();

            }else{
                var cp = Ext.getCmp('MyToolbar2');
                cp.show();
            }
        });
    },

    onWndPreciosAlertaBeforeRender: function(component, eOpts) {
        this.requiereAutorizacion();
    }

});
