/*
 * File: app/view/DlgPreciosAlertaViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgPreciosAlertaViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgexistenciaalerta',

    control: {
        "button#aceptaAlerta1": {
            click: 'aceptarAlertaClick'
        },
        "#passwordAutorizacionProductoPrecio1": {
            keyup: 'aceptarAlertaText'
        }
    },

    aceptarAlertaClick: function(button, e, eOpts) {
               this.validarAceptarAlerta();
    },

    aceptarAlertaText: function(textfield, e, eOpts) {
                        if (e.getKey()==Ext.event.Event.ENTER){
                                this.validarAceptarAlerta();
                            }
    },

    validarAceptarAlerta: function() {
        var request = new Object(); request.method="validaSupervisor"; request.params=[];
               request.params.push({"name":"imei","value":almacen.getApplication().SessionId},{"name":"USERNAME","value":Ext.ComponentMgr.get("passwordAutorizacionProductoPrecio1").getValue()});
               almacen.getApplication().loadData(request,function(response){
              if(response.status){
                   var controller=Ext.WindowManager.get("wndPreciosAlerta").parentController;
                   //controller.preguntarNoImpresiones();
                  controller.realizaAjustes();
                  Ext.WindowManager.get("wndPreciosAlerta").close();
              }else{
                  Ext.Msg.alert('', 'Usuario o contraseña incorrecto.');
              }
               });
    }

});
