/*
 * File: app/view/DlgReporteUbicacion.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgReporteUbicacion', {
    extend: 'Ext.window.Window',
    alias: 'widget.dlgreporteubicacion',

    requires: [
        'almacen.view.DlgReporteClasificacionesViewModel1',
        'almacen.view.DlgReporteClasificacionesViewController1',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'dlgreporteubicacion',
    viewModel: {
        type: 'dlgreporteubicacion'
    },
    height: 150,
    id: 'wndReporteUbicacion',
    width: 300,
    title: 'Listado de Clasificaciones',
    modal: true,

    items: [
        {
            xtype: 'combobox',
            id: 'cmbSucursalPedido',
            margin: '10 0 0 50',
            width: 200,
            displayField: 'SucursalOrigen',
            forceSelection: true,
            store: 'StoreSucursalPedido',
            valueField: 'claveSucursal',
            listeners: {
                beforerender: 'onCmbSucursalPedidoBeforeRender'
            }
        },
        {
            xtype: 'combobox',
            id: 'cmbTipoReporteUbicacion',
            margin: '10 0 0 50',
            width: 200,
            displayField: 'label',
            forceSelection: true,
            store: 'StoreGeneric',
            valueField: 'value',
            listeners: {
                beforerender: 'onCmbTipoReporteUbicacionBeforeRender'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    margin: '0 0 10 85',
                    text: 'Generar Reporte',
                    listeners: {
                        click: 'onGeneraReporteClick'
                    }
                }
            ]
        }
    ]

});