/*
 * File: app/view/DlgReporteClasificacionesViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgReporteClasificacionesViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgreporteubicacion',

    onCmbSucursalPedidoBeforeRender: function(component, eOpts) {
        var request = new Object(); request.method="consultasucursalpedido"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});

        almacen.getApplication().loadData(request,function(response){
            console.log(response);
            component.getStore().loadData(response.pedidos);
            if(response.pedidos.length < 2){
                Ext.Msg.alert("Error", "No hay más sucursales");
            } else{
                component.setValue(0.0);
            }
        });
    },

    onCmbTipoReporteUbicacionBeforeRender: function(component, eOpts) {
        var request = new Object(); request.method="tiporeporteubicacion"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});

        console.log(almacen.getApplication().currentSession);

        almacen.getApplication().loadData(request,function(response){
            console.log(response);
            component.getStore().loadData(response.items);
            tipoReporte = almacen.getApplication().currentSession.tipoReporte ? "1" : "0";
            component.setValue(tipoReporte);
        });
    },

    onGeneraReporteClick: function(button, e, eOpts) {
        var combo = Ext.getCmp('cmbSucursalPedido');
        var comboTipoReporte = Ext.getCmp('cmbTipoReporteUbicacion');

        var nombresucursal = combo.getRawValue();
        var clavesucursal = combo.getValue();

        var tipoReporte = comboTipoReporte.getValue();

        console.log(tipoReporte);


        var request = new Object(); request.method="reporteubicacion"; request.params=[];
        request.params.push({"name":"imei","value":almacen.getApplication().SessionId});
        request.params.push({"name":"clavesucursal","value":clavesucursal});
        request.params.push({"name":"nombreSucursal","value":nombresucursal});
        request.params.push({"name":"tipoReporte","value":tipoReporte});

        console.log(clavesucursal);
        console.log(nombresucursal);

        var wnd = Ext.getCmp("wndReporteUbicacion");

        var el = wnd.getEl();

        el.mask("Generando reporte...");

        almacen.getApplication().loadData(request,function(response){
            el.unmask();
            console.log(response);
            if(response.status){
                Ext.Msg.alert("Generación correcta", "Se descargará su reporte en breve");
                var controller=Ext.WindowManager.get("wndReporteUbicacion").parentController;
                controller.descargarReporte(5);
                Ext.WindowManager.get("wndReporteUbicacion").close();
            } else{
                Ext.Msg.alert("Error", response.msg);
            }
        }, function(response){
            el.unmask();
            console.log(response);
        });
    }

});
