/*
 * File: app/view/DlgValidaPasswordViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.DlgValidaPasswordViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dlgvalidapassword',

    control: {
        "button#btnCancelar": {
            click: 'btnCancelarClick'
        },
        "button#btnValidar": {
            click: 'btnValidarClick'
        },
        "#pwdValidacion": {
            keypress: 'pwdValidacionSubmit'
        }
    },

    btnCancelarClick: function(button, e, eOpts) {
                this.CancelarValidacion(button.ownerCt.ownerCt);
    },

    btnValidarClick: function(button, e, eOpts) {
               this.RealizarValidacion(button.ownerCt.ownerCt);
    },

    pwdValidacionSubmit: function(textfield, e, eOpts) {
            if (e.getKey() == Ext.event.Event.ENTER){
                this.RealizarValidacion(textfield.ownerCt);
            }
    },

    CancelarValidacion: function(parent) {
                if (parent.fnCancel){
                    parent.close();
                    parent.fnCancel();
                }else{

                    parent.close();
                }
    },

    RealizarValidacion: function(parent) {
        var request = {}; request.method="validarpassword"; request.params=[];
               request.params.push({"name":"imei","value":almacen.getApplication().SessionId},
                                   {"name":"USERNAME","value":Ext.ComponentMgr.get("pwdValidacion").getValue()},
                                   {"name":"TIPOUSUARIO","value":parent.currentValidationProfile});
               var prevParent = parent;
              almacen.getApplication().loadData(request,function(response){
              if(response.status){
                    if (prevParent.fnSuccess){
                        prevParent.close();
                        prevParent.fnSuccess(response);
                    }else{
                        prevParent.close();
                    }
              }else{
                  if (prevParent.fnIncorrect){
                      prevParent.fnIncorrect(response);
                  }else{
                     // prevParent.close();
                      Ext.Msg.alert('', 'Usuario o contraseña incorrecto.');
                      }
              }
               });
    }

});
