/*
 * File: app/view/panelCedis.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.panelCedis', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panelCedis',

    requires: [
        'almacen.view.panelInventariosViewModel1',
        'almacen.view.panelCedisViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    controller: 'panelcedis',
    viewModel: {
        type: 'panelcedis'
    },
    height: 600,
    width: 1000,
    layout: 'border',
    manageHeight: false,
    title: 'Pedidos por surtir',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            region: 'center',
            id: 'gridContainer',
            layout: 'fit',
            listeners: {
                afterrender: {
                    fn: 'onGridContainerAfterRender',
                    scope: 'controller'
                }
            }
        },
        {
            xtype: 'panel',
            region: 'south',
            height: 80,
            suspendLayout: true,
            title: '',
            titleCollapse: false,
            layout: {
                type: 'border',
                regionWeights: {
                    north: 20,
                    south: 10,
                    center: 0,
                    west: -5,
                    east: -20
                }
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    id: 'tbInventarios2',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'totalField',
                            width: 200,
                            fieldLabel: 'Total',
                            labelWidth: 50,
                            editable: false
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'toolbar',
                    region: 'center',
                    id: 'tbInventarios1',
                    items: [
                        {
                            xtype: 'button',
                            icon: 'resources/transfer.png',
                            text: 'Actualizar',
                            listeners: {
                                click: {
                                    fn: 'onButtonClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnGuardarPedidos',
                            icon: 'resources/save.png',
                            text: 'Guardar',
                            listeners: {
                                click: {
                                    fn: 'onBtnGuardarPedidosClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnConsultar1',
                            icon: 'resources/filter.gif',
                            text: 'Consultar Pedidos',
                            listeners: {
                                click: {
                                    fn: 'onBtnConsultar1Click',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'btnReportes',
                            icon: 'resources/table-edit.png',
                            text: 'Reportes',
                            listeners: {
                                click: {
                                    fn: 'onBtnConsultar1Click1',
                                    scope: 'controller'
                                },
                                beforerender: 'onBtnReportes2BeforeRender'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnImprimirPedidos',
                            icon: 'resources/print.png',
                            text: 'Imprimir Pedidos',
                            listeners: {
                                click: {
                                    fn: 'onBtnImprimirPedidosClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            id: 'generarExcel',
                            width: 120,
                            fieldLabel: '',
                            boxLabel: 'Generar Excel'
                        },
                        {
                            xtype: 'checkboxfield',
                            handler: function(checkbox, checked) {
                                var column_unidad = Ext.ComponentMgr.get("GridProductosCedis").down('headercontainer').getGridColumns()[2];

                                var column_precio = Ext.ComponentMgr.get("GridProductosCedis").down('headercontainer').getGridColumns()[3];

                                var column_existencia = Ext.ComponentMgr.get("GridProductosCedis").down('headercontainer').getGridColumns()[4];

                                console.log(checked);

                                if(checked){
                                    column_unidad.show();
                                    column_precio.show();
                                    column_existencia.show();
                                }else{
                                    if(!almacen.getApplication().currentSession.habilitaMostrarUnidad)
                                    column_unidad.hide();
                                    column_precio.hide();
                                    column_existencia.hide();
                                }
                            },
                            id: 'checkDetalles',
                            width: 150,
                            fieldLabel: '',
                            boxLabel: 'Vista Detalles'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'tbFecha',
            items: [
                {
                    xtype: 'form',
                    id: 'FormularioFiltro',
                    layout: 'column',
                    bodyPadding: 10,
                    manageHeight: false,
                    items: [
                        {
                            xtype: 'datefield',
                            id: 'fechaBusqueda',
                            itemId: 'fechaBusqueda',
                            width: 300,
                            fieldLabel: 'Fecha de Busqueda',
                            labelWidth: 120,
                            allowBlank: false,
                            emptyText: 'Fecha de Busqueda',
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'radiogroup',
                            id: 'radioFechaBusqueda',
                            itemId: 'radioFecha',
                            width: 160,
                            fieldLabel: '',
                            allowBlank: false,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    width: '',
                                    name: 'radioFecha',
                                    boxLabel: 'Registro',
                                    inputValue: '0'
                                },
                                {
                                    xtype: 'radiofield',
                                    width: '',
                                    name: 'radioFecha',
                                    boxLabel: 'Entrega',
                                    inputValue: '1'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            id: 'comboFechaBusqueda',
                            itemId: 'comboFecha',
                            width: 150,
                            fieldLabel: '',
                            allowBlank: false,
                            emptyText: 'Estado',
                            displayField: 'label',
                            queryMode: 'local',
                            store: 'StoreEstados',
                            valueField: 'value',
                            listeners: {
                                beforerender: {
                                    fn: 'cargarEstado',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnFiltrarBusqueda',
                            icon: 'resources/filter.gif',
                            text: 'Filtrar',
                            listeners: {
                                click: {
                                    fn: 'onBtnFiltrarBusquedaClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'label',
                    id: 'clock',
                    text: '',
                    listeners: {
                        afterrender: {
                            fn: 'onClockAfterRender',
                            scope: 'controller'
                        }
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'tbFecha1',
            items: [
                {
                    xtype: 'form',
                    hidden: true,
                    id: 'FormularioFiltro1',
                    layout: 'column',
                    bodyPadding: 10,
                    manageHeight: false,
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'idFecha1',
                            fieldLabel: 'Fecha de Busqueda:',
                            labelWidth: 125,
                            editable: false
                        },
                        {
                            xtype: 'radiogroup',
                            id: 'radioFechaBusqueda1',
                            width: 160,
                            fieldLabel: '',
                            allowBlank: false,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    width: '',
                                    name: 'radioFecha1',
                                    readOnly: true,
                                    boxLabel: 'Registro',
                                    inputValue: '0'
                                },
                                {
                                    xtype: 'radiofield',
                                    width: '',
                                    name: 'radioFecha1',
                                    readOnly: true,
                                    boxLabel: 'Entrega',
                                    inputValue: '1'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            id: 'comboFechaBusqueda1',
                            width: 150,
                            fieldLabel: '',
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'label',
                    hidden: true,
                    text: '(Filtro Aplicado)'
                }
            ]
        }
    ],

    onBtnReportes2BeforeRender: function(component, eOpts) {
        if(window.habilitabtnReportes == "visible"){
            component.setVisible(true);
        }
    }

});