/*
 * File: app/view/tbSupervision.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('almacen.view.tbSupervision', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.tbsupervision',

    requires: [
        'almacen.view.tbAjustesViewModel2',
        'almacen.view.tbAjustesViewController2',
        'Ext.button.Button'
    ],

    controller: 'tbsupervision',
    viewModel: {
        type: 'tbsupervision'
    },
    height: 50,
    width: 400,

    items: [
        {
            xtype: 'button',
            id: 'btnAjustes2',
            icon: 'resources/Search.png',
            text: 'Supervisar'
        }
    ]

});